version: '3.8'

services:
  app:
    build:
      context: strr-api
    ports:
      - "8080:8080"
    env_file:
      - strr-api/.env.local
    networks:
      - web_tier
      - service_tier

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - service_tier

volumes:
  postgres-data:

networks:
  web_tier:
    name: web_tier
  service_tier:
    name: service_tier
