name: STRR UI CI

on:
  pull_request:
    paths:
      - "strr-web/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./strr-web

jobs:
  strr-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "strr-ui"
      working_directory: "./strr-web"
      codecov_flag: "strrui"
