name: STRR UI Main CD

on:
  push:
    branches:
      - main
    paths:
      - "strr-web/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
        - dev
        - test
        - prod
      tagname:
        description: "Specify a previous version (git tag) to deploy"
        required: false
        default: ""

jobs:
  str-ui-main-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/ui-cd-pnpm.yaml@main
    with:
        environment: ${{ inputs.environment }}
        tagname: ${{ inputs.tagname }}
        working_directory: "./strr-web"
        package_name: "strr-main-app"
    secrets:
        APP_NAME: "strr-ui"
        OP_CONNECT_URL: ${{ secrets.OP_CONNECT_URL }}
        OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
